---
- name: 1. Downloading Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
- name: 2. Setting up nginx as a reverse proxy
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/defaults
  notify: Restart Nginx
