version: 2
updates:
  - package-ecosystem: "github-actions" #CI/CD pipelines
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" #dockerfile
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
