---
version: 2
updates:
  - package-ecosystem: "github-actions" # CI/CD pipelines
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # dockerfile
    directory: "/Kubernetes/app-src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
