# Using Jinja2 variables which are saved in the inventory/group_vars/all.yml file.
[proxy]
nginx ansible_host="{{ nginx_ip }}"

[app]
nodejs ansible_host="{{ app_ip }}"

[db]
database ansible_host="{{ db_private_ip }}"

#Seperating the two private EC2 instances as the ssh proxy command is needed for these ones
[private_servers:children]
app
db

# Specific ssh command and arguments for the app and db instances. Someone can edit them for their usecase.
[private_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ nginx_ip }} -i {{ key_location }} -o StrictHostKeyChecking=no"'
