[proxy]
nginx ansible_host="{{ nginx_ip }}"

[app]
nodejs ansible_host="{{ app_ip }}"

[db]
database ansible_host="{{ db_private_ip }}"

[private_servers:children]
app
db

[private_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ nginx_ip }} -i {{ key_location }} -o StrictHostKeyChecking=no"'
