---
- name: Install lightweight k3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s service is running
  systemd:
    name: k3s
    state: started
    enabled: yes

- name: Create directory for manifests
  file:
    path: /opt/k3s-manifests
    state: directory
    mode: '0755'

- name: Template and upload manifests
  ansible.builtin.template:
    src: "{{ playbook_dir }}/Kubernetes/manifests/app-manifests.yml"
    dest: /opt/k3s-manifests/app-manifests.yml

- name: Wait for Kubernetes to be ready
  shell: k3s kubectl get nodes
  register: nodes_ready
  until: nodes_ready.rc == 0 # checking return code
  retries: 5
  delay: 10

- name: Apply kubernets manifests - deploy app and service
  shell: k3s kubectl apply -f /opt/k3s-manifests/app-manifests.yml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml #in case of direcroty confusion for the amdinistator file
