---
- name: 1. Installing python and mysql
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes

#Changing mysql bind address from original 127.0.0.1 to 0.0.0.0 to be able to listen with node.

- name: 2. changing bind address
  ansible.builtin.lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0' #Using 0.0.0.0 is fine in this project
  notify: Restart mysql

- name: 4. Creating DB
  ansible.builtin.command: mysql -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
  changed_when: false

- name: 5. Creating user
  ansible.builtin.command: >
    mysql -e "CREATE USER IF NOT EXISTS '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_root_password }}';
    GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'%';
    FLUSH PRIVILEGES;"
  changed_when: false
