---
- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Restart CrowdSec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted
    enabled: yes
