---
# Modified Boilerplate adapted from: gmnikhil/k8s-boilerplate/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsec-node-deployment
  labels:
    app: awsec-node-app
spec:
  # Using two replicas here but can be changed to anything needed, I just have t3.small instances
  replicas: 2
  selector:
    matchLabels:
      app: awsec-node-app
  template:
    metadata:
      labels:
        app: awsec-node-app
    spec:
      containers:
        - name: awsec-node-container
          image: ghcr.io/kgjidodaj/awsec-node-app:latest
          imagePullPolicy: Always # for a pull to always happen since I am using latest version
          ports:
            - containerPort: 8080
          # The Jinja2 variables are taken from inventory/groups_var/all.yml
          env: # according to the app.js process.env
            - name: DB_HOST
              value: "{{ db_private_ip }}"
            - name: DB_USER
              value: "{{ db_user }}"
            - name: DB_PASSWORD
              value: "{{ db_root_password }}"
            - name: DB_NAME
              value: "{{ db_name }}"
---
# Modified Boilerplate adapted from: gmnikhil/k8s-boilerplate/basic-external_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: awsec-node-service
spec:
  selector:
    app: awsec-node-app
  type: NodePort
  # Aligning nodeport as the port nginx sends traffic to according to the template.
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000 #same as configured in main.tf as node.js is accepting data from nginx
