---
name: Ansible-Terraform Continuous Deployment
on:
  push:
    branches: ["main"]
jobs:
  integration-checks:
    name: Syntax and Security checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Ansible syntax check
        run: ansible-playbook site.yml --syntax-check
      - name: Terraform init and validate check
        working-directory: ./terraform-try # for the command to work
        run: terraform init -backend=false && terragorm validate #without backend connection as no credentials have been given yet

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          #Using the github secrets
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Install Ansible and init Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Provision AWS SSH key, Directory and password setup
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > ./aws-homelab.pem
          chmod 600 ./aws-homelab.pem
          mkdir -p ./inventory/group_vars
          echo "${{ secrets.VAULT_PASS }}" > ./.vault_pass

      - name: Terraform initialization and application
        working-directory: ./terraform-try
        run: |
          terraform init
          terraform plan # Because apply is hidden to a terr.log to prevent ip leakage
          terraform apply -auto-approve > terr.log

      - name: Extract IPs and mask logs
        #Masking the logs with ::add-mask:: and storing them in variables to be used in the next part of the code
        working-directory: ./terraform-try
        run: |
          NGINX_IP=$(terraform output -raw nginx_public_ip)
          APP_IP=$(terraform output -raw app_private_ip)
          DB_IP=$(terraform output -raw mysql_private_ip)
          echo "::add-mask::$NGINX_IP"
          echo "::add-mask::$APP_IP"
          echo "::add-mask::$DB_IP"
          echo "BASTION_IP=$NGINX_IP" >> $GITHUB_ENV
          echo "APP_IP=$APP_IP" >> $GITHUB_ENV
          echo "DB_IP=$DB_IP" >> $GITHUB_ENV

      - name: Place variables into group_vars/all.yml
        run: |
          cat <<EOF > ./inventory/group_vars/all.yml
          nginx_ip: "${BASTION_IP}"
          app_ip: "${APP_IP}"
          db_ip: "${DB_IP}"
          key_location: "./aws-homelab.pem"
          db_root_password: "${{ secrets.DB_PASSWORD }}"
          ansible_ssh_private_key_file: "./aws-homelab.pem"
          EOF

      - name: Execute Ansible Deployment
        run: ansible-playbook site.yml
        env:
          # Avoiding potential pauses for confirmation
          ANSIBLE_HOST_KEY_CHECKING: "False"
